In [3]:
import pandas as pd
import numpy as np
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
#creating a dataframe
df=pd.DataFrame(arr.reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"],dtype=float,copy=True)
df

      col1  col2  col3  col4
row1   0.0   1.0   2.0   3.0
row2   4.0   5.0   6.0   7.0
row3   8.0   9.0  10.0  11.0
row4  12.0  13.0  14.0  15.0
row5  16.0  17.0  18.0  19.0

In [12]:
#if we want to see the first 5 rows of the dataframe
df.head()

      col1  col2  col3  col4
row1   0.0   1.0   2.0   3.0
row2   4.0   5.0   6.0   7.0
row3   8.0   9.0  10.0  11.0
row4  12.0  13.0  14.0  15.0
row5  16.0  17.0  18.0  19.0

In [15]:
#if we want to see the last 5 rows of the dataframe
df.tail()

      col1  col2  col3  col4
row1   0.0   1.0   2.0   3.0
row2   4.0   5.0   6.0   7.0
row3   8.0   9.0  10.0  11.0
row4  12.0  13.0  14.0  15.0
row5  16.0  17.0  18.0  19.0

In [16]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#to see information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      float64
 1   col2    5 non-null      float64
 2   col3    5 non-null      float64
 3   col4    5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes

In [ ]:
#to see a statistical summary of the dataframe
df.describe()

            col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [20]:

#indexing
#can be done by coloumnname,rowindex[loc],rowindex columnindex number[iloc]
df.head()

      col1  col2  col3  col4
row1   0.0   1.0   2.0   3.0
row2   4.0   5.0   6.0   7.0
row3   8.0   9.0  10.0  11.0
row4  12.0  13.0  14.0  15.0
row5  16.0  17.0  18.0  19.0

In [24]:
#if we want to select specific columns
df[['col1','col2','col3']]

      col1  col2  col3
row1   0.0   1.0   2.0
row2   4.0   5.0   6.0
row3   8.0   9.0  10.0
row4  12.0  13.0  14.0
row5  16.0  17.0  18.0

In [25]:
type(df[['col1','col2','col3']])

pandas.core.frame.DataFrame

In [22]:
#if we want to select a specific column or single column
df['col1']

row1     0.0
row2     4.0
row3     8.0
row4    12.0
row5    16.0
Name: col1, dtype: float64

In [26]:
type(df['col1'])

pandas.core.series.Series

In [28]:
#indexing using loc or row
df.loc['row1']

col1    0.0
col2    1.0
col3    2.0
col4    3.0
Name: row1, dtype: float64

In [29]:
type(df.loc['row1'])

pandas.core.series.Series

In [30]:
df.loc[['row1','row2']]

      col1  col2  col3  col4
row1   0.0   1.0   2.0   3.0
row2   4.0   5.0   6.0   7.0

In [31]:
type(df.loc[['row1','row2']])

pandas.core.frame.DataFrame

In [32]:
df.head()

      col1  col2  col3  col4
row1   0.0   1.0   2.0   3.0
row2   4.0   5.0   6.0   7.0
row3   8.0   9.0  10.0  11.0
row4  12.0  13.0  14.0  15.0
row5  16.0  17.0  18.0  19.0

In [35]:
df.iloc[2:,1:3]

      col2  col3
row3   9.0  10.0
row4  13.0  14.0
row5  17.0  18.0

In [34]:
df.iloc[2:4]

      col1  col2  col3  col4
row3   8.0   9.0  10.0  11.0
row4  12.0  13.0  14.0  15.0

In [36]:
#convert the dataframe into array
df.iloc[:,:].values

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [38]:
#basic operations
df.isnull()

       col1   col2   col3   col4
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False
row5  False  False  False  False

In [ ]:
#tells the sum of how many null values are in each column
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [41]:
# np.nan is used to create null values in the dataframe
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["row1","row2"],columns=["col1","col2","col3"],dtype=float,copy=True)
df

      col1  col2  col3
row1   1.0   NaN   2.0
row2   1.0   3.0   4.0

In [42]:
df.isnull()

       col1   col2   col3
row1  False   True  False
row2  False  False  False

In [43]:
df.isnull().sum()

col1    0
col2    1
col3    0
dtype: int64

In [44]:
df=pd.DataFrame(data=[[1,np.nan,None],[1,3,0]],index=["row1","row2"],columns=["col1","col2","col3"],dtype=float,copy=True)
df

      col1  col2  col3
row1   1.0   NaN   NaN
row2   1.0   3.0   0.0

In [45]:
df.isnull().sum()

col1    0
col2    1
col3    1
dtype: int64

In [47]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,]],index=["row1","row2"],columns=["col1","col2","col3"],dtype=float,copy=True)
df

      col1  col2  col3
row1   1.0   NaN   2.0
row2   1.0   3.0   NaN

In [49]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,]],index=["row1","row2"],columns=["col1","col2","col3"],dtype=float,copy=True)
df

      col1  col2  col3
row1   1.0   NaN   2.0
row2   1.0   NaN   NaN